alist: https://www.focalors.ltd/
music: https://music.focalors.ltd/
palegacymod: https://focalors.ltd/%E5%BF%83%E7%8E%87%E5%A4%B1%E5%B8%B8/BetterLegacy%E7%B3%BB%E5%88%97
404: https://focalors.ltd/%E4%BF%A1%E6%81%AF%E8%AF%BE%E4%B8%93%E5%8C%BA/404
hoyomix-godmusic: https://music.focalors.ltd/playlist?id=12320511232
oracle: https://music.focalors.ltd/song?id=1920740889
unm-server: https://github.com/IamFurina/UNM-Server
neteaseapi: https://github.com/IamFurina/NeteaseCloudMusicApi
splayer-web: https://github.com/IamFurina/FreeNeteaseMusucPlayer
